### ISSUE TITLE
TypeError: Cannot allocate memory!

### ISSUE THREAD

**Issue by monbro** [binarymax/node-word2vec-native#1]
Hi, your package works perfectly and fast on my macbook (8GB RAM). But when I am trying to run my script on my remote server I get the following error (3 GB RAM):
```
distance.open('/opt/nlp/GoogleNews-vectors-negative300.bin',function(err){
         ^

TypeError: Cannot allocate memory!
    at Object.<anonymous> (/opt/nlp/node.js:3:10)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

My code is:

```
var distance = require('word2vec-native');

distance.open('/opt/nlp/GoogleNews-vectors-negative300.bin',function(err){
    if(!err) {
        console.log(distance.compare("king","queen"));
        console.log(distance.get("king"));

        console.log(distance.compare("ham","cheese"));
        console.log(distance.get("ham"));

        console.log(distance.compare("car","dog"));
        console.log(distance.get("dog"));
    }
});
```

**Comment by monbro** [comment]
Ah okay I see, if I upgrade to 8GB RAM it works :-S

**Comment by binarymax** [comment]
You already closed the issue, but it is likely because your binary vector file when loading can't fit in the available memory on the 3GB machine :)  I'm curious, what is the size (on disk) of GoogleNews-vectors-negative300.bin?

**Comment by monbro** [comment]
@binarymax just scroll down on https://code.google.com/archive/p/word2vec/ where you will find the file `GoogleNews-vectors-negative300.bin.gz` linked. But I found also https://github.com/eyaler/word2vec-slim which is a blessing and I can work witH <1GB RAM.

**Comment by monbro** [comment]
`GoogleNews-vectors-negative300.bin.gz` has 3.64GB
